export const ARTICLE_CONTENT = {
  'guide-developpeur-fullstack-2025': [
    { type: 'p', text: "Devenir développeur full-stack en 2025 est plus accessible que jamais. Les ressources gratuites abondent, les bootcamps en ligne se multiplient et la demande des entreprises reste forte. Voici la roadmap que j'aurais aimé avoir en débutant." },
    { type: 'h2', text: '1. Maîtriser les fondations (3–4 mois)' },
    { type: 'p', text: "Tout commence par HTML, CSS et JavaScript. Pas de raccourci possible : ces trois technologies sont la grammaire du web. Passez au moins 8 semaines à les maîtriser avant de toucher à un framework." },
    { type: 'ul', items: ['HTML5 sémantique et accessibilité', 'CSS Flexbox, Grid, animations', 'JavaScript ES6+ (promises, async/await, modules)', 'Git et GitHub pour le versioning'] },
    { type: 'h2', text: '2. Frontend — React et son écosystème' },
    { type: 'p', text: "React domine le marché en 2025. Apprenez les hooks, le state management avec Context ou Zustand, et intégrez des APIs REST. Next.js s'impose ensuite naturellement pour le SEO et les performances." },
    { type: 'ul', items: ['React 18 — hooks, Suspense, concurrent features', 'Routing avec React Router ou Next.js App Router', 'Fetch et Axios pour les appels API', 'Tailwind CSS ou SCSS pour le styling'] },
    { type: 'h2', text: '3. Backend — Node.js ou Laravel' },
    { type: 'p', text: "Pour le backend, deux chemins s'offrent à vous : Node.js/Express si vous voulez rester en JavaScript, ou Laravel (PHP) si vous préférez un framework batteries-included. Les deux sont excellents pour débuter." },
    { type: 'code', text: '// API REST simple avec Express\napp.get(\'/api/users\', async (req, res) => {\n  const users = await User.findAll()\n  res.json(users)\n})' },
    { type: 'h2', text: '4. Base de données' },
    { type: 'p', text: "SQL d'abord (MySQL ou PostgreSQL), NoSQL ensuite (MongoDB). La majorité des projets utilisent du SQL. Apprenez les jointures, les indexes et les transactions." },
    { type: 'h2', text: '5. DevOps de base' },
    { type: 'p', text: "En 2025, un développeur full-stack doit savoir déployer. Docker, les notions de CI/CD, et au moins un cloud provider (Vercel, Railway, ou un VPS Linux) sont incontournables." },
    { type: 'h2', text: 'Ressources recommandées' },
    { type: 'ul', items: ['The Odin Project (gratuit, complet)', 'freeCodeCamp — certifications gratuites', 'roadmap.sh — visualiser votre progression', 'MDN Web Docs — référence technique ultime'] },
  ],

  'prix-creation-site-web-maroc-2025': [
    { type: 'p', text: "La question revient dans chaque premier échange client : combien coûte un site web au Maroc ? La réponse honnête est : ça dépend. Mais voici les vrais facteurs qui font varier le budget." },
    { type: 'h2', text: '1. Type de site — la variable principale' },
    { type: 'ul', items: ['Site vitrine simple (5 pages) : 1 500 – 4 000 MAD', 'Site vitrine avec blog : 3 000 – 7 000 MAD', 'E-commerce WooCommerce/Shopify : 6 000 – 20 000 MAD', 'Application web sur mesure : 15 000 MAD et plus'] },
    { type: 'h2', text: '2. Design : template ou sur mesure ?' },
    { type: 'p', text: "Un design basé sur un template premium (Elementor, Divi) coûte moins cher mais ressemble à des milliers d'autres sites. Un design 100% sur mesure en Figma puis React/Next.js coûte plus cher mais vous démarque réellement de vos concurrents." },
    { type: 'h2', text: '3. Fonctionnalités spécifiques' },
    { type: 'ul', items: ['Formulaire de contact : inclus', 'Espace membre / authentification : +3 000 MAD', 'Paiement en ligne (CMI, PayPal) : +4 000 MAD', 'Multilingue : +1 500 MAD par langue', 'SEO technique avancé : +2 000 MAD'] },
    { type: 'h2', text: '4. Maintenance et hébergement' },
    { type: 'p', text: "Méfiez-vous des devis bas qui n'incluent pas l'hébergement, le nom de domaine ou la maintenance. Un site livré sans contrat de suivi peut rapidement poser des problèmes de sécurité ou de disponibilité." },
    { type: 'h2', text: '5. Référencement SEO' },
    { type: 'p', text: "Un beau site invisible sur Google ne sert à rien. L'optimisation SEO technique (Core Web Vitals, balises, sitemap, schema.org) devrait être incluse dans tout projet sérieux." },
    { type: 'h2', text: '6. Délais et urgence' },
    { type: 'p', text: "Un projet urgent avec livraison sous 2 semaines coûtera plus cher qu'un projet planifié sur 6 semaines. La disponibilité du développeur a un prix." },
    { type: 'h2', text: '7. Expérience du prestataire' },
    { type: 'p', text: "Un freelance débutant facturer 1 500 MAD pour un site vitrine, un expert avec portfolio solide en facturera 8 000. Le prix reflète souvent la qualité, la fiabilité et le suivi post-livraison." },
  ],

  'design-web-credibilite-marque': [
    { type: 'p', text: "Il faut 0,05 seconde à un visiteur pour se forger une première impression de votre site. En 50 millisecondes, votre crédibilité est jugée. C'est pour ça que le design web n'est pas un luxe — c'est un investissement commercial direct." },
    { type: 'h2', text: 'La règle des 3 secondes' },
    { type: 'p', text: "Si votre site met plus de 3 secondes à charger ou si le design est confus, 53% des visiteurs partent. Pour une TPE ou un freelance au Maroc, chaque visiteur perdu est un client potentiel perdu." },
    { type: 'h2', text: 'Cohérence visuelle = confiance' },
    { type: 'ul', items: ['Palette de couleurs limitée à 3 teintes max', 'Typographie cohérente (2 polices au maximum)', 'Espacement généreux — le blanc est un élément de design', 'Hiérarchie visuelle claire : titre, sous-titre, corps de texte'] },
    { type: 'h2', text: 'Performance = crédibilité technique' },
    { type: 'p', text: "Un site lent envoie le signal inconscient que votre entreprise est peu professionnelle. Les Core Web Vitals de Google (LCP < 2.5s, CLS < 0.1, FID < 100ms) ne sont pas seulement des critères SEO — ils reflètent l'expérience réelle de vos clients." },
    { type: 'h2', text: 'Mobile-first en 2025' },
    { type: 'p', text: "Au Maroc, 78% du trafic web vient des smartphones. Un site non optimisé pour mobile en 2025 est simplement inutilisable pour la majorité de vos clients." },
    { type: 'h2', text: 'Éléments de confiance à intégrer' },
    { type: 'ul', items: ['Témoignages clients visibles dès la homepage', 'Logos des clients ou partenaires', 'Certifications et badges de confiance', 'Adresse physique et numéro de téléphone en clair', 'HTTPS obligatoire (cadenas vert)'] },
    { type: 'h2', text: 'Le ROI du design professionnel' },
    { type: 'p', text: "Une étude Stanford montre que 75% des utilisateurs jugent la crédibilité d'une entreprise sur son design web. Investir 5 000 MAD dans un design professionnel qui convertit 2% de visiteurs supplémentaires rapporte souvent bien plus que l'investissement initial." },
  ],

  'docker-cicd-deploiements': [
    { type: 'p', text: "Chaque développeur a connu ce moment : 'Ça marche chez moi.' Docker résout ce problème. Couplé à un pipeline CI/CD, il transforme vos déploiements chaotiques en processus fiables et reproductibles." },
    { type: 'h2', text: 'Docker en 5 minutes' },
    { type: 'p', text: "Un conteneur Docker encapsule votre application et toutes ses dépendances dans une image portable. Peu importe que vous soyez sur Windows, Mac ou Linux — le comportement est identique." },
    { type: 'code', text: '# Dockerfile pour une app React\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\nFROM nginx:alpine\nCOPY --from=builder /app/build /usr/share/nginx/html\nEXPOSE 80' },
    { type: 'h2', text: 'docker-compose pour le développement local' },
    { type: 'p', text: "docker-compose permet de définir et lancer plusieurs services (app + base de données + cache) avec une seule commande. Idéal pour standardiser l'environnement de l'équipe." },
    { type: 'code', text: 'version: "3.9"\nservices:\n  app:\n    build: .\n    ports: ["3000:3000"]\n    depends_on: [db]\n  db:\n    image: mysql:8\n    environment:\n      MYSQL_ROOT_PASSWORD: secret\n      MYSQL_DATABASE: myapp' },
    { type: 'h2', text: 'CI/CD avec GitHub Actions' },
    { type: 'p', text: "GitHub Actions permet d'automatiser : les tests à chaque push, la construction de l'image Docker, et le déploiement sur votre serveur — le tout gratuitement pour les repos publics." },
    { type: 'ul', items: ['Push sur main → tests automatiques', 'Tests passent → build de l\'image Docker', 'Image pushée sur Docker Hub ou GHCR', 'Déploiement SSH sur VPS via docker-compose pull && up'] },
    { type: 'h2', text: 'Déploiement sur VPS Linux' },
    { type: 'p', text: "Un VPS à 5$/mois (DigitalOcean, Hetzner) avec Docker installé suffit pour la plupart des projets freelance. Nginx en reverse proxy, Certbot pour le SSL, et vous avez une infrastructure solide." },
  ],

  'seo-maroc-strategies-2025': [
    { type: 'p', text: "En 2025, apparaître en première page de Google.ma est l'un des leviers les plus puissants pour acquérir des clients au Maroc. Voici les stratégies concrètes qui fonctionnent." },
    { type: 'h2', text: '1. Audit technique d\'abord' },
    { type: 'p', text: "Avant toute optimisation de contenu, corrigez les problèmes techniques : vitesse de chargement, Core Web Vitals, balises manquantes, erreurs 404, structure des URLs. Un site lent ne se positionnera jamais bien." },
    { type: 'ul', items: ['Google Search Console — erreurs d\'indexation', 'PageSpeed Insights — score de performance', 'Screaming Frog — audit complet du site', 'Ahrefs ou SEMrush — analyse des positions'] },
    { type: 'h2', text: '2. Recherche de mots-clés locaux' },
    { type: 'p', text: "Les Marocains cherchent souvent en français ET en darija translittéré. Ciblez des requêtes locales : 'développeur web Casablanca', 'création site web Maroc prix', 'agence digitale Fès'." },
    { type: 'h2', text: '3. Contenu de qualité en français' },
    { type: 'p', text: "Google valorise le contenu long, informatif et original. Des articles de blog de 1 500 mots minimum, avec des titres H2/H3 structurés, du contenu unique et des liens internes, génèrent du trafic organique durable." },
    { type: 'h2', text: '4. Netlinking local' },
    { type: 'ul', items: ['Inscription sur les annuaires marocains (Yakeey, etc.)', 'Google Business Profile — obligatoire pour le local', 'Partenariats avec des blogs tech marocains', 'Mentions dans la presse digitale (Telquel, L\'Économiste)'] },
    { type: 'h2', text: '5. Schema.org et données structurées' },
    { type: 'p', text: "Les rich snippets (étoiles, FAQ, prix) augmentent le taux de clic même sans améliorer le classement. Schema.org LocalBusiness est particulièrement utile pour les freelances et TPE." },
  ],

  'laravel-vs-nodejs-api': [
    { type: 'p', text: "Vous démarrez un nouveau projet API et vous hésitez entre Laravel et Node.js ? Ce comparatif basé sur l'expérience terrain vous aidera à choisir selon votre contexte." },
    { type: 'h2', text: 'Laravel — le framework batteries-included' },
    { type: 'p', text: "Laravel (PHP) offre une expérience de développement remarquablement productive. Eloquent ORM, migrations, queues, authentification, broadcasting — tout est intégré et documenté. Idéal pour les équipes mixtes et les projets avec des délais courts." },
    { type: 'ul', items: ['Eloquent ORM — requêtes SQL élégantes sans écrire de SQL', 'Artisan — génération de code en ligne de commande', 'Laravel Sanctum/Passport pour l\'authentification API', 'Queues et jobs pour les tâches asynchrones', 'Documentation exemplaire sur laravel.com'] },
    { type: 'h2', text: 'Node.js/Express — la flexibilité totale' },
    { type: 'p', text: "Node.js brille pour les APIs temps réel (WebSockets), les microservices, et les équipes full-stack JavaScript. La performance raw est légèrement supérieure à PHP pour les opérations I/O-bound." },
    { type: 'ul', items: ['Event loop non-bloquant — parfait pour les I/O intensifs', 'WebSockets natifs avec Socket.io', 'npm — le plus grand écosystème de packages', 'Fastify ou Hono si la performance est critique'] },
    { type: 'h2', text: 'Performances comparées' },
    { type: 'p', text: "Pour 95% des projets, la performance n'est pas le critère différenciant — l'architecture et la base de données ont bien plus d'impact que le choix du framework. Laravel 11 avec Octane (Swoole) rivalise parfaitement avec Node.js." },
    { type: 'h2', text: 'Mon choix selon le contexte' },
    { type: 'ul', items: ['SaaS classique, équipe mixte → Laravel', 'Temps réel (chat, notifications live) → Node.js', 'Déjà du PHP/MySQL en production → Laravel', 'Stack 100% JS (React/Vue frontend) → Node.js', 'Délai court, prototype rapide → Laravel'] },
    { type: 'h2', text: 'Conclusion' },
    { type: 'p', text: "Il n'y a pas de mauvais choix entre les deux. Laravel est plus productif pour la plupart des projets CRUD classiques. Node.js gagne pour les cas d'usage temps réel. Maîtriser l'un ou l'autre vous rend déjà très employable sur le marché marocain." },
  ],
}
